import './globals.css';

import TopNav from "@/components/composite/TopNav";
import Footer from "@/components/composite/Footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <TopNav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
